server:
  port: 8080
  servlet:
    context-path: /api


spring:
  application:
    name: paiya-accountmanager
  profiles:
    active: dev, cloud


# Database
  data:
    mongodb:
      uri: mongodb+srv://tamsir225:L4fVcDT6Ynee4FMx@democluster.pfnfjyb.mongodb.net/paiya_accountmanager?retryWrites=true&w=majority&appName=DemoCluster

# OpenApi documentation
springdoc:
  api-docs:
    path: /doc
  swagger-ui:
    path: /swagger-ui.html