spring:

  # Database
  data:
    mongodb:
      uri: mongodb+srv://${paiyaaccountmanager_staging_dbusername}:${paiyaaccountmanager_staging_dbpassword}@democluster.pfnfjyb.mongodb.net/paiya_accountmanager?retryWrites=true&w=majority&appName=DemoCluster

  #Config Server
  config:
    import:
    - optional:configserver:https://paiya-config-server-c24vseuh2q-uc.a.run.app