name: Run mongodb container
description: 'Run mongodb container and expose port 27017'
inputs:
  root_username:
    description: "Mongodb root username"
    required: true
    default: paiya
  root_password:
    description: "Mongodb root password"
    required: true
    default: paiya
  database_name:
    description: "Mongodb database name"
    required: true
    default: paiya_accountmanager
runs:
  using: "composite"
  steps:
    - name: Run docker container
      shell: bash
      run: |
        echo username : "$INPUT_ROOT_USERNAME"
        echo password : "$INPUT_ROOT_PASSWORD"
        docker run --name mongodb -p 27017:27017 \
        -e MONGO_INITDB_ROOT_USERNAME=$INPUT_ROOT_USERNAME \
        -e MONGO_INITDB_ROOT_PASSWORD=$INPUT_ROOT_PASSWORD \
        -it mongodb/mongodb-community-server:latest
      env:
        INPUT_ROOT_USERNAME: ${{inputs.root_username}}
        INPUT_ROOT_PASSWORD: ${{inputs.root_password}}
        INPUT_DATABASE_NAME: ${{inputs.database_name}}