name: Run mongodb container
description: 'Run mongodb container and expose port 27017'
inputs:
  root_username:
    description: "Mongodb root username"
    required: true
    default: paiya
  root_password:
    description: "Mongodb root password"
    required: true
    default: paiya
  database_name:
    description: "Mongodb database name"
    required: true
    default: paiya_accountmanager
runs:
  using: "composite"
  steps:
    - name: Run docker container
      shell: bash
      run: |
        docker run --name mongodb -p 27017:27017 \
        -e MONGO_INITDB_ROOT_USERNAME=$INPUT_ROOT_USERNAME \
        -e MONGO_INITDB_ROOT_PASSWORD=$INPUT_ROOT_PASSWORD \
        -d mongodb/mongodb-community-server:latest
        docker exec -d mongodb mongosh "mongodb://localhost:27017" --username $INPUT_ROOT_USERNAME --password $INPUT_ROOT_PASSWORD \
        && use $INPUT_DATABASE_NAME \
        && db
      env:
        INPUT_ROOT_USERNAME: ${{inputs.root_username}}
        INPUT_ROOT_PASSWORD: ${{inputs.root_password}}