name: Deploy on Cloud Run

on:
  push:
    branches: [ "staging" ]

env:
  PROJECT_ID: 'paiya-413605' # TODO: update to your Google Cloud project ID
  REGION: 'us-central1' # TODO: update to your region
  SERVICE: 'paiya-accountmanager' # TODO: update to your service name
  WORKLOAD_IDENTITY_PROVIDER: 'projects/1025378920331/locations/global/workloadIdentityPools/github/providers/my-repo' # TODO: update to your workload identity provider
  
jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332' # actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

			- name: Setup Gradle
				uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

			- name: Build and generate a jar file
				run: ./gradlew build